import type { City, Faq } from './types';

export const faqs: Faq[] = [
  // Patio covers (existing copy)
  { id: 'pc-cost', question: 'How much does a patio cover cost in Dallas-Fort Worth in 2026?', answer: 'In the DFW market, most patio covers run $8,000 to $25,000+. A basic 12x12 lean-to (shed-style) cover starts around $8,000-$12,000, a mid-size gable cover with a shingled roof matched to your home typically lands between $14,000 and $20,000, and large custom designs with tongue-and-groove ceilings, lighting, and fans can exceed $25,000. Every Structure1 estimate is free, itemized, and includes permits and engineering.' },
  { id: 'pc-gable-vs-leanto', question: "What's the difference between a gable and a lean-to patio cover?", answer: "A lean-to (shed-style) cover attaches to your home with a single sloped roof — it's the most cost-effective option and works well under existing eaves. A gable cover has a peaked, A-frame roofline that adds height, airflow, and a more custom architectural look, and it's the better choice for taller ceilings or larger patios. Gable covers typically cost 20-35% more than a comparable lean-to." },
  { id: 'pc-permits', question: 'Do you handle patio cover permits in Dallas, Plano, Frisco, and other DFW cities?', answer: 'Yes. Nearly every city in the DFW metroplex — including Dallas, Fort Worth, Plano, Frisco, McKinney, and Arlington — requires a building permit for a patio cover. Structure1 handles the full permit process on every project: drawings, engineering letters where required, submission, and inspections. Permit approval usually takes 1-2 weeks depending on the city.' },
  { id: 'pc-roof-match', question: "Will my patio cover match my home's existing roof?", answer: 'Yes. On solid-roof covers we install architectural shingles color-matched to your existing roof so the addition looks original to the house, and we tie the new roofline into your home\'s structure correctly — flashing, drainage, and attachment points are where inexperienced builders cause leaks. Standing seam metal and polycarbonate panel roofs are also available.' },
  { id: 'pc-timeline', question: 'How long does patio cover installation take?', answer: "Construction itself takes 3-7 days for most patio covers once permits are approved and materials arrive. End to end — contract, permit approval (1-2 weeks), material procurement, and build — plan on 2-4 weeks. We confirm a build date before work starts and keep one crew on your project until it's finished." },
  { id: 'pc-with-concrete', question: 'Do you build patio covers with concrete included?', answer: "Yes, and it's the most cost-effective way to do a full outdoor living project. Because we self-perform both structures and concrete, we can pour a new stamped concrete patio and build the cover above it in one mobilization — one permit package, one crew, one timeline." },
  { id: 'pc-materials', question: 'What materials do you use for patio covers?', answer: "We primarily build with premium-grade Western Red Cedar and pressure-treated lumber, which are ideal for the Texas climate due to their natural resistance to warping, splitting, and insects. For roofing, we use architectural shingles matched to your home's existing roof, standing seam metal, or polycarbonate panels depending on your preference. All hardware is galvanized or stainless steel for long-term durability." },
  { id: 'pc-storms', question: 'Are your patio covers built to withstand Texas storms?', answer: 'Absolutely. Every patio cover we build is engineered to meet or exceed local building codes for wind resistance and structural load requirements. We use heavy-duty post anchors, hurricane ties, and proper footing depths to ensure your structure can withstand severe Texas weather including high winds and hail. Our 2-year workmanship warranty covers any structural issues, and our builds are designed to last 20+ years with minimal maintenance.' },
  { id: 'pc-value', question: "Will a patio cover increase my home's value?", answer: "Yes. A well-built patio cover typically provides a 50-80% return on investment and can increase your home's overall value by making your outdoor space functional year-round. In the competitive DFW real estate market, outdoor living spaces are one of the top features buyers look for. Beyond resale value, you'll enjoy immediate benefits like lower cooling costs (shading windows reduces solar heat) and expanded living space." },
  // Patio covers: polycarbonate and free-standing builds
  { id: 'pc-solid-vs-poly', question: "What's the difference between a solid-roof and a polycarbonate patio cover?", answer: 'The roof. A solid-roof cover (shingled or metal) provides complete protection from sun and rain and the deepest shade. A polycarbonate cover uses clear or tinted panels over cedar rafters, so it keeps rain off while letting natural light through. An open-rafter cover with no panels gives partial, dappled shade. For Texas weather, many homeowners prefer a solid roof for full protection, while polycarbonate offers a bright middle ground.' },
  { id: 'pc-poly-cost', question: 'How much does a polycarbonate patio cover cost in Dallas-Fort Worth?', answer: 'A cedar patio cover with a polycarbonate roof typically runs $10,000 to $18,000 in DFW depending on size, post count, and extras like lighting and fans. Open-rafter covers without roofing cost less. Every estimate is free and itemized, and includes the permit package.' },
  { id: 'pc-freestanding', question: 'Can a patio cover be free-standing instead of attached to the house?', answer: 'Yes. We build both. Attached covers tie into your home\'s structure and work well over an existing patio; free-standing covers sit on their own steel-anchored footings and can be placed by a pool, over a dining area, or anywhere in the yard. Our Lewisville project is a free-standing build.' },
  // Concrete (existing copy)
  { id: 'con-cost', question: 'How much does stamped concrete cost in Dallas-Fort Worth?', answer: 'Stamped concrete in DFW typically runs $12 to $22 per square foot installed, depending on the pattern, number of colors, and site prep required. A standard 400 sq ft stamped patio usually lands between $5,000 and $8,500. Plain broom-finish concrete runs $7-$11 per square foot. Structure1 provides free itemized estimates so you can compare finishes side by side.' },
  { id: 'con-patterns', question: 'What stamped concrete patterns and colors do you offer?', answer: 'We install the most popular DFW patterns — ashlar slate, random stone, wood plank, herringbone brick, and cobblestone — in integral and antiqued color combinations that complement Texas home exteriors. During your estimate we bring pattern samples and photos of local installs so you can see exactly how a finish looks on a real project.' },
  { id: 'con-thickness', question: 'How thick should a concrete patio or driveway be in Texas?', answer: 'A patio slab should be a minimum of 4 inches thick over compacted base, and driveways should be 5-6 inches with steel reinforcement. North Texas clay soil moves with moisture changes, so proper base compaction, rebar (not just wire mesh), and correctly spaced control joints matter more here than in most markets. We engineer every pour for expansive soil.' },
  { id: 'con-cracks', question: 'Will my concrete crack?', answer: 'All concrete develops hairline cracks as it cures — the goal is controlling where. We cut control joints on a proper grid so movement happens at the joints instead of across the surface, use reinforcement suited to the slab\'s use, and pour at the right thickness over compacted base. Our 2-year workmanship warranty covers structural failures, and correctly installed slabs last 30+ years in DFW.' },
  { id: 'con-cure', question: 'How long before I can use my new concrete?', answer: 'You can walk on new concrete after 24-48 hours, place furniture after 7 days, and drive on a new driveway after 7-10 days. Full cure strength takes 28 days. For stamped and colored finishes we apply sealer after the slab has cured, which adds color depth and protects against stains and UV fading — resealing every 2-3 years keeps it looking new.' },
  { id: 'con-replace', question: 'Do you replace existing patios and driveways?', answer: 'Yes. Tear-out and replacement is a large share of our concrete work in Dallas-Fort Worth — we demo the old slab, haul it off, re-compact the base, and pour new. Replacement is usually the right call when a slab has settled, heaved at the joints, or has widespread cracking, since overlays on a failed slab inherit its problems.' },
  // Stamped concrete (new)
  { id: 'sc-vs-pavers', question: 'Is stamped concrete better than pavers?', answer: 'Stamped concrete is a single reinforced slab, so there are no joints for weeds or shifting, and it costs less per square foot than most paver installs. Pavers can be lifted and reset individually. On North Texas clay soil, a properly reinforced slab with control joints is the more stable choice for patios and pool surrounds.' },
  { id: 'sc-sealing', question: 'How often does stamped concrete need to be sealed?', answer: 'We seal every stamped slab after it cures. Resealing every 2-3 years keeps color depth and protects against stains and UV fading. It is a one-day job we can schedule for you.' },
  // Driveways & walkways (new)
  { id: 'dw-thickness', question: 'How thick is a Structure1 driveway?', answer: 'Driveways are poured 5-6 inches thick with steel rebar over compacted base, with control joints cut on a correct grid. That is the specification North Texas expansive soil needs; thinner slabs with wire mesh are where most driveway failures start.' },
  { id: 'dw-drive-on', question: 'When can I park on a new driveway?', answer: 'Walk on it after 24-48 hours and drive on it after 7-10 days. Full cure strength takes 28 days.' },
  { id: 'dw-finish', question: 'What finishes are available for driveways and walkways?', answer: 'Broom finish ($7-$11 per square foot) is the standard for driveways and walkways: clean, textured, and slip-resistant. Stamped borders or full stamped finishes ($12-$22 per square foot) add a decorative edge, and staining and sealing refresh existing slabs.' },
  // Outdoor living (new, no prices)
  { id: 'ol-scope', question: 'What does an outdoor living project include?', answer: 'Most outdoor living projects combine a patio cover with a new stamped or broom-finish concrete patio, plus lighting and ceiling fans. Because we self-perform both the structure and the concrete, the whole project runs on one permit package, one crew, and one timeline.' },
  { id: 'ol-phases', question: 'Can I build an outdoor living space in phases?', answer: 'Yes. Many homeowners pour the patio first and add the cover later, or build the cover now and add lighting and fans afterward. We design the first phase so the next one fits without rework.' },
  // Remodeling & new builds (new, no prices)
  { id: 'rm-scope', question: 'What kinds of remodeling and new-build work does Structure1 take on?', answer: 'Additions, full backyard makeovers, and interior remodels in select DFW markets, alongside our core patio cover and concrete work. Tell us about the project and we will let you know quickly whether it is a fit.' },
  { id: 'rm-permits', question: 'Do you handle permits for additions and remodels?', answer: 'Yes. Drawings, engineering, city submission, and inspections are part of every Structure1 project, including additions and remodels.' },
  // Planning (new, from existing process copy)
  { id: 'plan-start', question: 'How soon can a project start?', answer: 'Most projects begin 2-3 weeks after contract signing, which covers permit approval and material procurement. Fall and winter often have the shortest wait times.' },
  { id: 'plan-payment', question: 'How do payments work?', answer: 'We require a deposit to secure materials and scheduling, with the remaining balance due upon project completion and your satisfaction. Many clients phase larger projects to manage cost; we can discuss the right structure during your free estimate.' },
  { id: 'plan-warranty', question: 'What does the warranty cover?', answer: 'Every project carries a 2-year workmanship warranty covering structural issues with the structure or slab.' },
];

export const faqsFor = (ids: string[]): Faq[] => ids.map((id) => faqs.find((f) => f.id === id)).filter((f): f is Faq => Boolean(f));

export const cityFaqs = (city: City): Faq[] => [
  { id: `${city.slug}-cost`, question: `How much does a patio cover cost in ${city.name}, TX?`, answer: `Patio covers in ${city.name} typically run $8,000 to $25,000+ depending on size, style, and finishes. A basic lean-to cover starts around $8,000-$12,000, while a custom gable design with a shingled roof matched to your home usually lands between $14,000 and $25,000. Stamped concrete patios run $12-$22 per square foot. Structure1 provides free, itemized on-site estimates anywhere in ${city.name}.` },
  { id: `${city.slug}-permit`, question: `Do I need a permit for a patio cover in ${city.name}?`, answer: city.permitNote },
  { id: `${city.slug}-services`, question: `What services does Structure1 offer in ${city.name}?`, answer: 'We build custom patio covers (gable, lean-to, polycarbonate, and free-standing designs) and stamped or broom-finish concrete for patios, driveways, and walkways — all engineered for North Texas weather and backed by a 2-year workmanship warranty.' },
  { id: `${city.slug}-start`, question: `How soon can you start a project in ${city.name}?`, answer: `Most projects begin 2-3 weeks after contract signing, which covers permit approval and material procurement. Construction itself takes 3-7 days for most patio covers and 1-2 weeks for larger outdoor living projects. We serve ${city.name} year-round — fall and winter often have the shortest wait times.` },
  ...faqsFor(city.faqIds),
];
