import type { Service, ServiceSlug } from './types';

export const services: Service[] = [
  {
    slug: 'patio-covers',
    name: 'Patio Covers',
    navLabel: 'Patio Covers',
    navBlurb: 'Gable, lean-to, and polycarbonate designs',
    seo: {
      title: 'Patio Cover Builder in Dallas-Fort Worth, TX | Free Estimates',
      description: 'Custom patio covers in Dallas-Fort Worth: gable, lean-to & polycarbonate designs. Permits handled, engineered for Texas wind, 2-year warranty. Free estimates.',
    },
    hero: 'gable-dfw',
    gallery: ['gable-mckinney-2', 'leanto-forney-2', 'gable-mckinney-ceiling'],
    lead: 'Covered outdoor rooms with roofing matched to your home, engineered for North Texas wind, and built by one in-house crew.',
    overview: [
      'Structure1 Construction is a patio cover builder serving the entire Dallas-Fort Worth metroplex — Dallas, Fort Worth, Plano, Frisco, McKinney, Arlington, and 20+ surrounding cities. We design and build gable covers with shingles matched to your existing roof, cost-effective lean-to designs, and polycarbonate-roof pergolas, all engineered for North Texas wind loads and built from Western Red Cedar on steel-anchored footings.',
      'Every project includes permits and engineering — we handle drawings, city submission, and inspections in every DFW municipality.',
    ],
    options: [
      { name: 'Lean-To (Shed)', blurb: 'Single slope attached to the home. Clean, low-profile. Best for smaller patios, budget-conscious builds, and low rooflines.', range: '$8,000 – $14,000' },
      { name: 'Gable (A-Frame)', blurb: 'Peaked roofline with shingles matched to your home. Custom and architectural. Best for larger patios, height, airflow, and resale value.', range: '$14,000 – $25,000+' },
      { name: 'Polycarbonate Pergola', blurb: 'Clear or tinted panels over cedar rafters. Open and bright. Rain protection without losing natural light.', range: '$10,000 – $18,000' },
    ],
    reasons: [
      { title: 'Usable outdoors in Texas heat', blurb: 'Shade over the patio and the windows behind it lowers surface temperatures and cooling costs.' },
      { title: 'Looks original to the house', blurb: 'Color-matched shingles, posts sized to the home, and a roofline tied in correctly with flashing and drainage.' },
      { title: 'Lighting, fans, and ceilings', blurb: 'Tongue-and-groove ceilings, recessed lighting, and ceiling fans turn a cover into a room.' },
      { title: 'Adds value', blurb: 'Outdoor living space is one of the top features DFW buyers look for.' },
    ],
    construction: [
      'Footings: steel-anchored posts set in engineered footings sized for North Texas soil and wind load.',
      'Structure: Western Red Cedar posts and beams, hurricane ties, and galvanized or stainless hardware.',
      'Roof: architectural shingles matched to your home, standing seam metal, or polycarbonate panels; flashed and tied into the existing roofline.',
      'Finish: tongue-and-groove ceilings, stain or paint, recessed lighting, and fan blocking as specified.',
      'Permits and inspections handled by us from drawings through final.',
    ],
    faqIds: ['pc-cost', 'pc-gable-vs-leanto', 'pc-permits', 'pc-roof-match', 'pc-timeline', 'pc-with-concrete', 'pc-materials', 'pc-storms'],
    relatedServices: ['pergolas', 'stamped-concrete', 'outdoor-living'],
    topic: 'patio-covers',
  },
  {
    slug: 'pergolas',
    name: 'Pergolas',
    navLabel: 'Pergolas',
    navBlurb: 'Cedar pergolas, attached or free-standing',
    seo: {
      title: 'Cedar Pergola Builder in Dallas-Fort Worth, TX | Structure1',
      description: 'Custom cedar pergolas in Dallas-Fort Worth, attached or free-standing, with open rafters or polycarbonate roofing. Permits included, 2-year warranty. Free estimates.',
    },
    hero: 'pergola-lewisville-1',
    gallery: ['pergola-plano-complete', 'pergola-fort-worth', 'pergola-midlothian'],
    lead: 'Open, bright structures in Western Red Cedar, with the option of polycarbonate roofing for rain protection without losing the light.',
    overview: [
      'A pergola gives you defined, partially shaded outdoor space with an open, airy feel. Structure1 builds cedar pergolas across Dallas-Fort Worth, attached to the home or free-standing on their own footings, with open rafters or clear and tinted polycarbonate panels.',
      'Our pergola projects in Plano, Fort Worth, Lewisville, and Midlothian include recessed lighting, ceiling fans, and privacy back walls. Every build is engineered for North Texas wind and includes the permit and HOA package.',
    ],
    options: [
      { name: 'Open-rafter pergola', blurb: 'Classic cedar rafters and beams for dappled shade and a defined outdoor room.' },
      { name: 'Polycarbonate-roof pergola', blurb: 'Clear or tinted panels over cedar rafters: rain protection with natural light.', range: '$10,000 – $18,000' },
      { name: 'Free-standing', blurb: 'Set on its own steel-anchored footings by a pool, dining area, or anywhere in the yard.' },
      { name: 'With back wall', blurb: 'A framed back wall adds privacy and wind protection, as on our Midlothian project.' },
    ],
    reasons: [
      { title: 'Light without the heat', blurb: 'Rafters and polycarbonate panels filter sun while keeping the space open.' },
      { title: 'Defines the space', blurb: 'A pergola turns an open slab into a dining room, lounge, or poolside retreat.' },
      { title: 'Grows with the yard', blurb: 'Add fans, lighting, or a privacy wall now or later without rework.' },
    ],
    construction: [
      'Footings: concrete piers with steel post anchors, sized for the span and North Texas soil.',
      'Frame: Western Red Cedar posts, beams, and rafters with galvanized or stainless hardware and hurricane ties.',
      'Roof: open rafters, or polycarbonate panels on purlins with proper drainage slope.',
      'Finish: stain or paint, recessed lighting and fan blocking as specified.',
      'Permit and HOA submissions handled by us.',
    ],
    faqIds: ['per-vs-cover', 'per-cost', 'per-freestanding', 'per-permit'],
    relatedServices: ['patio-covers', 'stamped-concrete', 'outdoor-living'],
    topic: 'pergolas',
  },
  {
    slug: 'concrete',
    name: 'Concrete',
    navLabel: 'Concrete',
    navBlurb: 'Patios, slabs, and replacements',
    seo: {
      title: 'Concrete Contractor in Dallas-Fort Worth, TX | Patios & Slabs',
      description: 'Concrete patios, slabs, driveways & replacements in Dallas-Fort Worth. Engineered for North Texas clay soil, 2-year warranty, free itemized estimates.',
    },
    hero: 'reno-pergola-turf-wide',
    gallery: ['stamped-patio-forney-1', 'stamped-driveway-dallas', 'concrete-slab-pour'],
    lead: 'Patios, slabs, driveways, and replacements built for expansive North Texas clay: compacted base, steel rebar, correct thickness, and control joints on a real grid.',
    overview: [
      'Structure1 Construction is a concrete contractor serving Dallas-Fort Worth — patios, driveways, walkways, and decorative finishes across Dallas, Plano, Frisco, McKinney, Arlington, Fort Worth, and the surrounding metroplex. North Texas clay soil expands and contracts with every wet-dry cycle, so we build for it: compacted base, steel reinforcement (rebar, not wire mesh), proper slab thickness, and control joints cut on a correct grid.',
      'Concrete also pairs naturally with our patio covers: one crew pours the slab and builds the structure above it, on one permit and one timeline.',
    ],
    options: [
      { name: 'Broom finish', blurb: 'Clean, textured, slip-resistant. Driveways, walkways, pool surrounds.', range: '$7 – $11 / sq ft' },
      { name: 'Stamped concrete', blurb: 'Stone, slate, brick, and wood-plank patterns. Patios, outdoor living areas, front entries.', range: '$12 – $22 / sq ft' },
      { name: 'Stained / sealed', blurb: 'Rich color depth on new or existing slabs. Refreshing patios and covered outdoor rooms.' },
      { name: 'Tear-out and replacement', blurb: 'Demo, haul-off, re-compacted base, and a new slab for settled, heaved, or cracked concrete.' },
    ],
    reasons: [
      { title: 'Built for clay soil', blurb: 'Base compaction, rebar, and joint spacing matter more in North Texas than almost anywhere.' },
      { title: 'One crew with the structure', blurb: 'Pour the patio and build the cover above it in one mobilization.' },
      { title: 'Lasts decades', blurb: 'Correctly installed slabs last 30+ years in DFW, backed by our 2-year workmanship warranty.' },
    ],
    construction: [
      'Excavation and base: remove organics, compact base material, set forms to drain away from the house.',
      'Reinforcement: steel rebar on chairs; 4-inch minimum for patios, 5-6 inches for driveways.',
      'Pour and finish: broom, stamped, or smooth; control joints cut on a proper grid.',
      'Cure and seal: walk after 24-48 hours, furniture after 7 days, vehicles after 7-10 days; sealer applied after cure on decorative finishes.',
    ],
    faqIds: ['con-cost', 'con-patterns', 'con-thickness', 'con-cracks', 'con-cure', 'con-replace'],
    relatedServices: ['stamped-concrete', 'driveways-walkways', 'patio-covers'],
    topic: 'concrete',
  },
  {
    slug: 'stamped-concrete',
    name: 'Stamped Concrete',
    navLabel: 'Stamped Concrete',
    navBlurb: 'Stone, slate, brick, and wood-plank patterns',
    seo: {
      title: 'Stamped Concrete Contractor in Dallas-Fort Worth, TX | Structure1',
      description: 'Stamped concrete patios, pool decks & entries in Dallas-Fort Worth. Ashlar slate, random stone, wood plank & brick patterns. $12–$22/sq ft. Free estimates.',
    },
    hero: 'stamped-patio-forney-1',
    gallery: ['stamped-flagstone', 'stamped-wood-plank', 'stamped-herringbone'],
    lead: 'The look of stone, slate, brick, or wood plank in a single reinforced slab, in integral and antiqued colors chosen to match your home.',
    overview: [
      'Stamped finishes are our concrete specialty. We install the most popular DFW patterns — ashlar slate, random stone, wood plank, herringbone brick, and cobblestone — in integral and antiqued color combinations that complement Texas home exteriors.',
      'During your estimate we bring pattern samples and photos of local installs so you can see exactly how a finish looks on a real project. Stamped patios are often poured together with a patio cover so the whole outdoor room is one job.',
    ],
    options: [
      { name: 'Ashlar slate', blurb: 'Large rectangular stones with a natural slate texture.' },
      { name: 'Random stone / flagstone', blurb: 'Irregular stones for a natural, hand-laid look.' },
      { name: 'Wood plank', blurb: 'Board-width planks with grain texture, often used under covered areas.' },
      { name: 'Herringbone or running-bond brick', blurb: 'Classic brick layouts for entries, borders, and walkways.' },
    ],
    reasons: [
      { title: 'Stone look, slab performance', blurb: 'No joints for weeds or shifting; one reinforced slab engineered for clay soil.' },
      { title: 'Costs less than pavers or stone', blurb: 'Installed pricing of $12 to $22 per square foot, itemized in your free estimate.' },
      { title: 'Pairs with a cover', blurb: 'Pour the patio and build the structure above it in one project.' },
    ],
    construction: [
      'Base and reinforcement exactly as our standard concrete: compacted base, rebar, 4-inch minimum.',
      'Integral color mixed into the concrete, then a release color and the stamp pattern applied while the slab is plastic.',
      'Control joints placed to follow the pattern wherever possible.',
      'Sealer applied after cure; reseal every 2-3 years to keep color depth.',
    ],
    faqIds: ['con-cost', 'con-patterns', 'sc-vs-pavers', 'sc-sealing', 'con-cracks'],
    relatedServices: ['concrete', 'patio-covers', 'driveways-walkways'],
    topic: 'stamped-concrete',
  },
  {
    slug: 'driveways-walkways',
    name: 'Driveways & Walkways',
    navLabel: 'Driveways & Walkways',
    navBlurb: 'Replacement and new pours, broom or stamped',
    seo: {
      title: 'Concrete Driveways & Walkways in Dallas-Fort Worth, TX | Structure1',
      description: 'Concrete driveway and walkway installation and replacement in Dallas-Fort Worth. 5-6 inch reinforced slabs, broom or stamped finishes, 2-year warranty. Free estimates.',
    },
    hero: 'driveway-dallas',
    gallery: ['stamped-driveway-dallas', 'stamped-herringbone', 'concrete-slab-pour'],
    lead: 'New driveways, walkways, and replacements poured thick enough and reinforced correctly for North Texas soil.',
    overview: [
      'Driveways take vehicle loads on soil that moves with every wet-dry cycle, so we pour them 5-6 inches thick with steel rebar over compacted base and cut control joints on a correct grid. Walkways and front entries get the same base preparation at patio thickness.',
      'Tear-out and replacement is a large share of our concrete work in Dallas-Fort Worth: we demo the old slab, haul it off, re-compact the base, and pour new. Our Dallas driveway is a full stone-pattern stamp with a contrasting stamped border.',
    ],
    options: [
      { name: 'Broom-finish driveway', blurb: 'The standard: clean, textured, slip-resistant.', range: '$7 – $11 / sq ft' },
      { name: 'Stamped border or full stamp', blurb: 'A decorative band or a full stone or brick pattern.', range: '$12 – $22 / sq ft' },
      { name: 'Walkways and entries', blurb: 'Front walks, side paths, and porch extensions matched to the house.' },
      { name: 'Driveway replacement', blurb: 'Demo, haul-off, re-compacted base, new reinforced slab.' },
    ],
    reasons: [
      { title: 'Stops the heaving', blurb: 'Correct thickness, rebar, and joints keep slabs from cracking across the surface.' },
      { title: 'Curb appeal', blurb: 'A clean new drive or a stamped border changes the front of the house.' },
      { title: 'Warranty-backed', blurb: '2-year workmanship warranty on every pour.' },
    ],
    construction: [
      'Demo and haul-off of the old slab where replacing.',
      'Compacted base, forms set to drain, rebar on chairs.',
      '5-6 inch pour for driveways, 4-inch for walkways; broom or stamped finish.',
      'Control joints cut on a proper grid; vehicles after 7-10 days.',
    ],
    faqIds: ['dw-thickness', 'dw-drive-on', 'dw-finish', 'con-replace', 'con-cracks'],
    relatedServices: ['concrete', 'stamped-concrete'],
    topic: 'driveways-walkways',
  },
  {
    slug: 'outdoor-living',
    name: 'Outdoor Living',
    navLabel: 'Outdoor Living',
    navBlurb: 'Cover, patio, lighting, and fans as one project',
    seo: {
      title: 'Outdoor Living Spaces in Dallas-Fort Worth, TX | Structure1',
      description: 'Complete outdoor living projects in Dallas-Fort Worth: patio cover or pergola, stamped concrete patio, lighting, and fans built by one crew on one timeline. Free estimates.',
    },
    hero: 'reno-kitchen-pergola-turf',
    gallery: ['reno-pergola-kitchen-corner', 'reno-kitchen-roof-underside', 'leanto-forney-2'],
    lead: 'The whole backyard room, designed together: structure, slab, ceiling, lighting, and fans from one crew on one permit and one timeline.',
    overview: [
      'Most of our best projects are not a single item. They are a covered structure, a new stamped concrete patio underneath it, a finished ceiling, recessed lighting, and ceiling fans, planned as one outdoor room instead of pieced together over years.',
      'Because Structure1 self-performs both structures and concrete, the entire project runs on one permit package, one crew, and one schedule. Our Forney project pairs a lean-to cover with a stamped patio; our McKinney gable cover includes a tongue-and-groove ceiling and fan.',
    ],
    options: [
      { name: 'Cover + patio', blurb: 'A gable, lean-to, or polycarbonate structure over a new stamped or broom-finish slab.' },
      { name: 'Ceilings, lighting, fans', blurb: 'Tongue-and-groove ceilings, recessed lighting, and fan blocking coordinated with your electrician.' },
      { name: 'Privacy and wind walls', blurb: 'Framed back walls on pergolas and covers for shelter and privacy.' },
      { name: 'Phased builds', blurb: 'Patio now, cover later, designed so the second phase fits without rework.' },
    ],
    reasons: [
      { title: 'One design, one timeline', blurb: 'Structure and slab are engineered together so footings, drainage, and layout line up.' },
      { title: 'Year-round use', blurb: 'Shade, fans, and lighting make the space usable through Texas summers and evenings.' },
      { title: 'One point of contact', blurb: 'The same lead carpenter from estimate to final walk-through.' },
    ],
    construction: [
      'Site visit and a single drawing set covering the slab and the structure.',
      'Permit and HOA package submitted once for the whole project.',
      'Concrete poured and cured, then the structure built on it by the same crew.',
      'Ceiling, lighting, and fan finish work; final walk-through.',
    ],
    faqIds: ['ol-scope', 'ol-phases', 'pc-with-concrete', 'pc-timeline'],
    relatedServices: ['patio-covers', 'pergolas', 'stamped-concrete'],
    topic: 'outdoor-living',
    ownerReview: true,
  },
  {
    slug: 'remodeling',
    name: 'Remodeling & New Builds',
    navLabel: 'Remodeling & New Builds',
    navBlurb: 'Additions and remodels in select markets',
    seo: {
      title: 'Home Additions & Remodeling in Dallas-Fort Worth, TX | Structure1',
      description: 'Additions, backyard makeovers, and interior remodels in select Dallas-Fort Worth markets from the Structure1 crew. Permits and engineering handled. Free estimates.',
    },
    hero: 'gable-dallas-dusk',
    gallery: ['carport-melissa-1', 'gable-mckinney-build', 'pergola-plano-framing'],
    lead: 'Additions, full backyard makeovers, and interior remodels in select DFW markets, handled by the same in-house crew and permit process as our outdoor work.',
    overview: [
      'Alongside patio covers and concrete, Structure1 takes on additions, full backyard transformations, and interior remodels in select Dallas-Fort Worth markets. The approach is the same: drawings and engineering up front, permits handled by us, one crew on site, and a clean, communicative build.',
      'Tell us about the project. We will let you know quickly whether it is a fit and what the next step looks like.',
    ],
    options: [
      { name: 'Additions', blurb: 'Covered structures, carports, and room additions tied into the existing home.' },
      { name: 'Backyard transformations', blurb: 'Structure, concrete, lighting, and finishes planned as one project.' },
      { name: 'Interior remodels', blurb: 'Select interior work in markets where our crew is already active.' },
    ],
    reasons: [
      { title: 'Same crew, same standard', blurb: 'The lead carpenter and process you would get on a patio cover.' },
      { title: 'Permits and engineering included', blurb: 'Drawings, submission, and inspections are part of the job.' },
      { title: 'Honest scoping', blurb: 'If a project is not a fit for us, we say so at the first call.' },
    ],
    construction: [
      'Scoping call and site visit.',
      'Drawings, engineering, and permit submission.',
      'Build with one crew and daily updates.',
      'Final walk-through and warranty.',
    ],
    faqIds: ['rm-scope', 'rm-permits', 'plan-start', 'plan-payment'],
    relatedServices: ['outdoor-living', 'patio-covers', 'concrete'],
    topic: 'remodeling',
    ownerReview: true,
  },
];

export const getService = (slug: string): Service | undefined => services.find((s) => s.slug === slug);
export const serviceSlugs = services.map((s) => s.slug) as ServiceSlug[];
